<?php
// Basic routing configuration
$routes = [
    '/' => 'HomeController@index',
    '/home' => 'HomeController@homePage',
    '/login' => 'AuthController@login',
    '/register' => 'AuthController@register',
    '/logout' => 'AuthController@logout',
    '/forgot-password' => 'AuthController@forgotPassword',
    '/verify-otp' => 'AuthController@verifyOtp',
    '/reset-password' => 'AuthController@resetPassword',
    '/client/dashboard' => 'ClientController@dashboard',
    '/client/home' => 'ClientController@home',
    '/client/events' => 'ClientController@browseEvents',
    '/client/browse-events' => 'ClientController@browseEvents',
    '/client/events/view' => 'ClientController@viewEvent',
    '/organizer/dashboard' => 'OrganizerController@dashboard',
    '/organizer/events' => 'OrganizerController@events',
    '/organizer/events/create' => 'OrganizerController@createEvent',
    '/organizer/events/store' => 'OrganizerController@storeEvent',
    '/organizer/events/view' => 'OrganizerController@viewEvent',
    '/organizer/events/edit' => 'OrganizerController@editEvent',
    '/organizer/events/update' => 'OrganizerController@updateEvent',
    '/organizer/events/delete' => 'OrganizerController@deleteEvent',
    '/organizer/bookings' => 'OrganizerController@bookings',
    '/organizer/bookings/view' => 'OrganizerController@viewBooking',
    '/organizer/bookings/approve' => 'OrganizerController@approveBooking',
    '/organizer/bookings/cancel' => 'OrganizerController@cancelBooking',
    '/organizer/messages' => 'OrganizerController@messages',
    '/client/book' => 'ClientController@bookEvent',
    '/client/book/store' => 'ClientController@storeBooking',
    '/client/bookings' => 'ClientController@myBookings',
    '/client/bookings/cancel' => 'ClientController@cancelBooking',
    '/client/bookings/view' => 'ClientController@viewBookingDetails',
    '/client/profile/update' => 'ClientController@updateProfile',
    '/client/profile/delete-picture' => 'ClientController@deleteProfilePicture',

    // Admin Routes
    '/admin/dashboard' => 'AdminController@dashboard',
    '/admin/users' => 'AdminController@users',
    '/admin/users/update-role' => 'AdminController@updateUserRole',
    '/admin/users/toggle-block' => 'AdminController@toggleUserBlock',
    
    '/admin/events' => 'AdminController@events',
    '/admin/events/create' => 'AdminController@createEvent',
    '/admin/events/store' => 'AdminController@storeEvent',
    '/admin/events/view' => 'AdminController@viewEvent',
    '/admin/events/edit' => 'AdminController@editEvent',
    '/admin/events/update' => 'AdminController@updateEvent',
    '/admin/events/delete' => 'AdminController@deleteEvent',

    '/admin/bookings' => 'AdminController@bookings',
    '/admin/bookings/view' => 'AdminController@viewBooking',
    '/admin/bookings/approve' => 'AdminController@approveBooking',
    '/admin/bookings/cancel' => 'AdminController@cancelBooking',
    '/admin/profile/update' => 'AdminController@updateProfile',
    '/admin/profile/delete-picture' => 'AdminController@deleteProfilePicture',
    
    '/organizer/profile/update' => 'OrganizerController@updateProfile',
    '/organizer/profile/delete-picture' => 'OrganizerController@deleteProfilePicture',
];
