<?php
// Basic routing configuration
$routes = [
    '/' => 'HomeController@index',
    '/login' => 'AuthController@login',
    '/register' => 'AuthController@register',
    '/logout' => 'AuthController@logout',
    '/forgot-password' => 'AuthController@forgotPassword',
    '/verify-otp' => 'AuthController@verifyOtp',
    '/reset-password' => 'AuthController@resetPassword',
    '/client/dashboard' => 'ClientController@dashboard',
    '/client/events' => 'ClientController@browseEvents',
    '/client/browse-events' => 'ClientController@browseEvents',
    '/client/events/view' => 'ClientController@viewEvent',
    '/organizer/dashboard' => 'OrganizerController@dashboard',
    '/organizer/events' => 'OrganizerController@events',
    '/organizer/events/create' => 'OrganizerController@createEvent',
    '/organizer/events/store' => 'OrganizerController@storeEvent',
    '/organizer/events/view' => 'OrganizerController@viewEvent',
    '/organizer/events/edit' => 'OrganizerController@editEvent',
    '/organizer/events/update' => 'OrganizerController@updateEvent',
    '/organizer/events/delete' => 'OrganizerController@deleteEvent',
    '/organizer/bookings' => 'OrganizerController@bookings',
    '/organizer/bookings/view' => 'OrganizerController@viewBooking',
    '/organizer/bookings/approve' => 'OrganizerController@approveBooking',
    '/organizer/bookings/cancel' => 'OrganizerController@cancelBooking',
    '/client/book' => 'ClientController@bookEvent',
    '/client/book/store' => 'ClientController@storeBooking',
    '/client/bookings' => 'ClientController@myBookings',
    '/client/bookings/cancel' => 'ClientController@cancelBooking',
    '/client/bookings/view' => 'ClientController@viewBookingDetails',
];
