<?php
// Basic routing configuration
$routes = [
    '/' => 'HomeController@index',
    '/home' => 'HomeController@homePage',
    '/login' => 'AuthController@login',
    '/register' => 'AuthController@register',
    '/logout' => 'AuthController@logout',
    '/forgot-password' => 'AuthController@forgotPassword',
    '/verify-otp' => 'AuthController@verifyOtp',
    '/reset-password' => 'AuthController@resetPassword',
    '/client/dashboard' => 'ClientController@home',
    '/client/home' => 'ClientController@home',
    '/client/events' => 'ClientController@browseEvents',
    '/client/browse-events' => 'ClientController@browseEvents',
    '/client/events/view' => 'ClientController@viewEvent',
    '/organizer' => 'OrganizerController@dashboard',
    '/organizer/dashboard' => 'OrganizerController@dashboard',
    '/organizer/events' => 'OrganizerController@events',
    '/organizer/events/create' => 'OrganizerController@createEvent',
    '/organizer/events/store' => 'OrganizerController@storeEvent',
    '/organizer/events/view' => 'OrganizerController@viewEvent',
    '/organizer/events/edit' => 'OrganizerController@editEvent',
    '/organizer/events/update' => 'OrganizerController@updateEvent',
    '/organizer/events/delete' => 'OrganizerController@deleteEvent',
    '/organizer/bookings' => 'OrganizerController@bookings',
    '/organizer/bookings/view' => 'OrganizerController@viewBookingDetails',
    '/organizer/bookings/approve' => 'OrganizerController@approveBooking',
    '/organizer/bookings/cancel' => 'OrganizerController@cancelBooking',
    '/organizer/bookings/mark-paid' => 'OrganizerController@markBookingPaid',
    '/organizer/tickets' => 'OrganizerController@tickets',
    '/organizer/messages' => 'OrganizerController@messages',
    '/client/book' => 'ClientController@bookEvent',
    '/client/book/store' => 'ClientController@storeBooking',
    '/client/bookings' => 'ClientController@myBookings',
    '/client/tickets' => 'ClientController@myTickets',
    '/client/bookings/cancel' => 'ClientController@cancelBooking',
    '/client/bookings/view' => 'ClientController@viewBookingDetails',
    '/client/profile/update' => 'ClientController@updateProfile',
    '/client/profile/delete-picture' => 'ClientController@deleteProfilePicture',
    '/client/ticket' => 'ClientController@viewTicket',

    // Payment Routes
    '/client/payment/checkout' => 'PaymentController@checkout',
    '/client/payment/process' => 'PaymentController@process',
    '/client/payment/success' => 'PaymentController@success',
    '/client/payment/cancel' => 'PaymentController@cancel',
    '/client/payment/error' => 'PaymentController@error',

    // Admin Routes
    '/admin' => 'AdminController@dashboard',
    '/admin/dashboard' => 'AdminController@dashboard',
    '/admin/users' => 'AdminController@users',
    '/admin/users/update-role' => 'AdminController@updateUserRole',
    '/admin/users/toggle-block' => 'AdminController@toggleUserBlock',

    '/admin/events' => 'AdminController@events',
    '/admin/events/create' => 'AdminController@createEvent',
    '/admin/events/store' => 'AdminController@storeEvent',
    '/admin/events/view' => 'AdminController@viewEvent',
    '/admin/events/edit' => 'AdminController@editEvent',
    '/admin/events/update' => 'AdminController@updateEvent',
    '/admin/events/delete' => 'AdminController@deleteEvent',

    // Admin Bookings
    '/admin/bookings' => 'AdminController@bookings',
    '/admin/bookings/view' => 'AdminController@viewBookingDetails',
    '/admin/bookings/approve' => 'AdminController@approveBooking',
    '/admin/bookings/cancel' => 'AdminController@cancelBooking',
    '/admin/bookings/mark-paid' => 'AdminController@markBookingPaid',
    '/admin/tickets' => 'AdminController@tickets',

    '/admin/profile/update' => 'AdminController@updateProfile',
    '/admin/profile/delete-picture' => 'AdminController@deleteProfilePicture',

    '/organizer/profile/update' => 'OrganizerController@updateProfile',
    '/organizer/profile/delete-picture' => 'OrganizerController@deleteProfilePicture',

    // Notification Routes
    '/notifications' => 'NotificationController@index',
    '/notifications/read' => 'NotificationController@markAsRead',
    '/notifications/unread' => 'NotificationController@markAsUnread',
    '/notifications/mark-all-read' => 'NotificationController@deleteAll',
    '/notifications/mark-all-unread' => 'NotificationController@markAllAsUnread',
    '/notifications/delete' => 'NotificationController@deleteOne',
    '/notifications/clear-all' => 'NotificationController@clearAll',
    '/notifications/all' => 'NotificationController@allNotifications',
    '/notifications/all-json' => 'NotificationController@allNotificationsJson',
    '/notifications/counts' => 'NotificationController@getCountsJson',

    // Feedback Pages
    '/client/feedback' => 'ClientController@feedback',
    '/admin/feedback' => 'AdminController@feedback',
    '/organizer/feedback' => 'OrganizerController@feedback',
];
