-- Create a default Admin (Password: admin123)
INSERT INTO users (fullname, email, password, role, is_verified)
VALUES ('System Admin', 'admin@ems.com', 'admin123', 'admin', 1);

-- Create a default Organizer (Password: org123)
INSERT INTO users (fullname, email, password, role, is_verified)
VALUES ('Event Organizer', 'organizer@ems.com', 'org123', 'organizer', 1);

-- Create 25 Sample Events (organizer_id = 2)
INSERT INTO events (organizer_id, title, description, category, status, image_path, event_date, venue_name, venue_location, bookings_count, packages) VALUES
(2, 'Summer Music Festival', 'A big summer concert featuring top artists from around the world. Live music, food stalls, and amazing atmosphere.', 'concert', 'active', 'public/assets/images/concert.png', '2026-06-15 18:00:00', 'Grand Arena Stadium', 'Kathmandu, Nepal', 12, '{"basic":{"name":"Basic","price":1500,"features":["General Seating","Food Voucher"]},"standard":{"name":"Standard","price":3000,"features":["Reserved Seating","Food & Drinks","Meet & Greet"]},"premium":{"name":"Premium","price":5000,"features":["VIP Seating","All Access","Backstage Pass"]}}'),
(2, 'Rock Night Live', 'An electrifying rock night with local and international rock bands performing their greatest hits.', 'concert', 'active', 'public/assets/images/concert.png', '2026-07-20 20:00:00', 'The Underground Club', 'Pokhara, Nepal', 8, '{"basic":{"name":"Basic","price":1200,"features":["Standing Entry"]},"standard":{"name":"Standard","price":2500,"features":["Front Row Access","Free Drinks"]},"premium":{"name":"Premium","price":4000,"features":["Backstage Pass","Meet the Band"]}}'),
(2, 'Jazz Evening', 'Smooth jazz performances under the stars. Perfect for a relaxing evening with friends and family.', 'concert', 'active', 'public/assets/images/concert.png', '2026-08-10 19:00:00', 'Lake Side Pavilion', 'Pokhara, Nepal', 5, '{"basic":{"name":"Basic","price":1000,"features":["Seating"]},"standard":{"name":"Standard","price":2000,"features":["Seating","One Drink"]},"premium":{"name":"Premium","price":3500,"features":["VIP Seating","Full Catering"]}}'),
(2, 'Traditional Nepali Wedding', 'A grand traditional Nepali wedding ceremony with cultural rituals and celebrations.', 'wedding', 'active', 'public/assets/images/wedding.png', '2026-06-25 08:00:00', 'Royal Garden Hall', 'Kathmandu, Nepal', 15, '{"basic":{"name":"Basic","price":50000,"features":["Standard Decoration","Basic Catering"]},"standard":{"name":"Standard","price":100000,"features":["Premium Decoration","Full Catering","Photography"]},"premium":{"name":"Premium","price":200000,"features":["Royal Decoration","VIP Catering","Full Package"]}}'),
(2, 'Royal Wedding Celebration', 'A luxurious wedding celebration with modern and traditional fusion.', 'wedding', 'active', 'public/assets/images/wedding.png', '2026-09-15 09:00:00', 'Mountain View Resort', 'Nagarkot, Nepal', 10, '{"basic":{"name":"Basic","price":75000,"features":["Decoration","Catering"]},"standard":{"name":"Standard","price":150000,"features":["Premium Decoration","Full Catering"]},"premium":{"name":"Premium","price":300000,"features":["Royal Package","All Inclusive"]}}'),
(2, 'John Birthday Bash', 'A fun-filled birthday party with games, music, and delicious cake for kids.', 'birthday', 'active', 'public/assets/images/other_events.png', '2026-06-05 14:00:00', 'Fun Zone Arena', 'Kathmandu, Nepal', 20, '{"basic":{"name":"Basic","price":5000,"features":["Games","Cake","Return Gift"]},"standard":{"name":"Standard","price":8000,"features":["Games","Magic Show","Food"]},"premium":{"name":"Premium","price":15000,"features":["Full Package","Entertainment","Photography"]}}'),
(2, 'Sweet 16 Party', 'A glamorous teenage birthday celebration with music, dance, and photo booth.', 'birthday', 'active', 'public/assets/images/other_events.png', '2026-07-12 18:00:00', 'Sky Lounge', 'Kathmandu, Nepal', 30, '{"basic":{"name":"Basic","price":10000,"features":["DJ","Food"]},"standard":{"name":"Standard","price":15000,"features":["DJ","Food","Photo Booth"]},"premium":{"name":"Premium","price":25000,"features":["Full Party Package","VIP Treatment"]}}'),
(2, 'Golden Jubilee Birthday', 'A milestone 50th birthday celebration with family and friends.', 'birthday', 'active', 'public/assets/images/other_events.png', '2026-08-25 12:00:00', 'Heritage Banquet', 'Bhaktapur, Nepal', 25, '{"basic":{"name":"Basic","price":25000,"features":["Decoration","Food"]},"standard":{"name":"Standard","price":40000,"features":["Premium Decoration","Full Catering"]},"premium":{"name":"Premium","price":60000,"features":["Grand Celebration","All Inclusive"]}}'),
(2, 'Tech Summit 2026', 'Annual technology conference featuring industry leaders, workshops, and networking.', 'corporate', 'active', 'public/assets/images/meeting.png', '2026-07-30 09:00:00', 'Convention Center', 'Kathmandu, Nepal', 50, '{"basic":{"name":"Basic","price":5000,"features":["Entry Only"]},"standard":{"name":"Standard","price":10000,"features":["All Sessions","Lunch"]},"premium":{"name":"Premium","price":20000,"features":["VIP Access","Networking Dinner"]}}'),
(2, 'Startup Pitch Night', 'An evening where startups pitch to investors and mentors.', 'corporate', 'active', 'public/assets/images/meeting.png', '2026-08-15 17:00:00', 'Innovation Hub', 'Pokhara, Nepal', 35, '{"basic":{"name":"Basic","price":0,"features":["Watching"]},"standard":{"name":"Standard","price":500,"features":["Networking"]},"premium":{"name":"Premium","price":1000,"features":["Investor Meet"]}}'),
(2, 'Annual Business Gala', 'A formal evening of networking and awards for business leaders.', 'corporate', 'active', 'public/assets/images/meeting.png', '2026-09-05 18:00:00', 'Grand Hotel Ballroom', 'Kathmandu, Nepal', 40, '{"basic":{"name":"Basic","price":15000,"features":["Dinner","Entry"]},"standard":{"name":"Standard","price":25000,"features":["Dinner","Networking"]},"premium":{"name":"Premium","price":40000,"features":["VIP Table","Awards Priority"]}}'),
(2, 'Dashain Family Reunion', 'A grand Dashain gathering with traditional rituals and celebrations.', 'cultural', 'active', 'public/assets/images/cultural.png', '2026-10-12 10:00:00', 'Cultural Hall', 'Kathmandu, Nepal', 60, '{"basic":{"name":"Basic","price":15000,"features":["Basic Catering"]},"standard":{"name":"Standard","price":30000,"features":["Full Catering","Programs"]},"premium":{"name":"Premium","price":50000,"features":["Grand Package","All Inclusive"]}}'),
(2, 'Losar Tibetan Festival', 'Celebration of Tibetan New Year with traditional dance, food, and cultural exhibits.', 'cultural', 'active', 'public/assets/images/cultural.png', '2026-02-14 09:00:00', 'Tibetan Cultural Center', 'Kathmandu, Nepal', 45, '{"basic":{"name":"Basic","price":300,"features":["Entry"]},"standard":{"name":"Standard","price":500,"features":["Entry","Food"]},"premium":{"name":"Premium","price":1000,"features":["VIP Seating","Cultural Show"]}}'),
(2, 'Maha Shivaratri Night', 'A spiritual evening of prayers, music, and cultural performances.', 'cultural', 'active', 'public/assets/images/cultural.png', '2026-02-27 20:00:00', 'Pashupatinath Temple Area', 'Kathmandu, Nepal', 100, '{"basic":{"name":"Basic","price":0,"features":["Open Entry"]},"standard":{"name":"Standard","price":200,"features":["Special Seating"]},"premium":{"name":"Premium","price":500,"features":["VIP Darshan"]}}'),
(2, 'Board Meeting Q2', 'Quarterly board meeting for strategic planning and review.', 'meeting', 'active', 'public/assets/images/meeting.png', '2026-06-30 10:00:00', 'Corporate Board Room', 'Kathmandu, Nepal', 10, '{"basic":{"name":"Basic","price":0,"features":["Board Members Only"]},"standard":{"name":"Standard","price":0,"features":["Presentation Tools"]},"premium":{"name":"Premium","price":0,"features":["Full Support"]}}'),
(2, 'Team Building Retreat', 'A day of team activities, workshops, and bonding for company employees.', 'meeting', 'active', 'public/assets/images/meeting.png', '2026-07-25 08:00:00', 'Mountain Resort', 'Nagarkot, Nepal', 30, '{"basic":{"name":"Basic","price":1500,"features":["Activities","Lunch"]},"standard":{"name":"Standard","price":2500,"features":["Activities","Meals","Transport"]},"premium":{"name":"Premium","price":4000,"features":["Full Package","Accommodation"]}}'),
(2, 'Bratabandha Ceremony', 'A traditional Bratabandha (coming of age) ceremony with cultural rituals.', 'bratabandha', 'active', 'public/assets/images/bratabandha.png', '2026-08-20 07:00:00', 'Traditional Mandir', 'Patan, Nepal', 40, '{"basic":{"name":"Basic","price":50000,"features":["Basic Rituals","Prasad"]},"standard":{"name":"Standard","price":80000,"features":["Full Rituals","Prasad","Food"]},"premium":{"name":"Premium","price":150000,"features":["Grand Ceremony","All Inclusive"]}}'),
(2, 'Bratabandha Celebration', 'Modern celebration of the sacred thread ceremony with family and friends.', 'bratabandha', 'active', 'public/assets/images/bratabandha.png', '2026-09-28 08:00:00', 'Garden Venue', 'Bhaktapur, Nepal', 35, '{"basic":{"name":"Basic","price":60000,"features":["Decoration","Food"]},"standard":{"name":"Standard","price":100000,"features":["Premium Decoration","Catering"]},"premium":{"name":"Premium","price":180000,"features":["Grand Package"]}}'),
(2, 'Family Reunion Gala', 'A family reunion bringing together relatives from across the country.', 'family', 'active', 'public/assets/images/family.png', '2026-10-05 12:00:00', 'Family Resort', 'Chitwan, Nepal', 50, '{"basic":{"name":"Basic","price":20000,"features":["Basic Catering"]},"standard":{"name":"Standard","price":40000,"features":["Full Catering","Activities"]},"premium":{"name":"Premium","price":70000,"features":["All Inclusive"]}}'),
(2, 'Anniversary Celebration', '25th wedding anniversary celebration with family and friends.', 'family', 'active', 'public/assets/images/family.png', '2026-11-15 18:00:00', 'Garden Restaurant', 'Kathmandu, Nepal', 25, '{"basic":{"name":"Basic","price":30000,"features":["Decoration","Food"]},"standard":{"name":"Standard","price":50000,"features":["Premium Decoration","Catering"]},"premium":{"name":"Premium","price":80000,"features":["Grand Celebration"]}}'),
(2, 'Kids Science Fair', 'An interactive science fair where kids showcase projects and experiments.', 'other', 'active', 'public/assets/images/other_events.png', '2026-07-10 10:00:00', 'Science Center', 'Kathmandu, Nepal', 100, '{"basic":{"name":"Basic","price":0,"features":["Entry"]},"standard":{"name":"Standard","price":200,"features":["Entry","Materials"]},"premium":{"name":"Premium","price":500,"features":["Hands-on Sessions"]}}'),
(2, 'Charity Food Festival', 'A charity event featuring food from various cuisines with all proceeds going to charity.', 'other', 'active', 'public/assets/images/other_events.png', '2026-08-30 11:00:00', 'City Park', 'Pokhara, Nepal', 200, '{"basic":{"name":"Basic","price":300,"features":["Food Coupons"]},"standard":{"name":"Standard","price":500,"features":["Extra Coupons","Drink"]},"premium":{"name":"Premium","price":1000,"features":["All Access","Souvenir"]}}'),
(2, 'Art Exhibition Opening', 'Showcasing contemporary art from local and international artists.', 'other', 'active', 'public/assets/images/other_events.png', '2026-09-20 16:00:00', 'Art Gallery', 'Kathmandu, Nepal', 50, '{"basic":{"name":"Basic","price":0,"features":["RSVP Entry"]},"standard":{"name":"Standard","price":500,"features":["Gallery Tour"]},"premium":{"name":"Premium","price":1500,"features":["Artist Meet","Collection"]}}'),
(2, 'Yoga & Wellness Retreat', 'A day of yoga sessions, meditation, and wellness workshops.', 'other', 'active', 'public/assets/images/other_events.png', '2026-10-25 06:00:00', 'Wellness Resort', 'Nagarkot, Nepal', 30, '{"basic":{"name":"Basic","price":1500,"features":["Yoga Sessions"]},"standard":{"name":"Standard","price":2500,"features":["Yoga","Meals"]},"premium":{"name":"Premium","price":4000,"features":["Full Wellness Package"]}}'),
(2, 'Sports Day Competition', 'Various sports competitions including cricket, football, and volleyball.', 'other', 'active', 'public/assets/images/other_events.png', '2026-11-08 08:00:00', 'Sports Complex', 'Kathmandu, Nepal', 150, '{"basic":{"name":"Basic","price":500,"features":["Participation"]},"standard":{"name":"Standard","price":1000,"features":["Tournament Entry","T-Shirt"]},"premium":{"name":"Premium","price":2000,"features":["Full Package","Awards"]}}');